import { useEffect, useState } from "react";
import "./productionCoverageAudit.css";

const API_BASE=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/+$/,"");
const TOKEN_KEY="agendai_admin_token";
const CLIENTE_ID=1;

type Cause={key:string;label:string;total:number;high:number;medium:number;low:number};
type Calibration={ok:boolean;canonicalReceptionSessions:number;classifiedReceptionSessions:number;delta:number;authority:string};
type TopItem={label:string;total:number};
type Drill={key:string;label:string;total:number;topCoverages:TopItem[];topSpecialties:TopItem[];subSignals:TopItem[]};
type Data={totals:Record<string,number>;calibration?:Calibration;causes:Cause[];drilldown?:Drill[];methodology:{source:string;privacy:string;caution:string}};

async function apiGet(path:string,token:string){const r=await fetch(`${API_BASE}${path}?t=${Date.now()}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"},cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.details||p?.error||`HTTP ${r.status}`);return p.data as Data;}

function MiniList({title,items,total}:{title:string;items:TopItem[];total:number}){return <div><h3>{title}</h3>{items.length?<div className="prod-audit-table-wrap"><table><thead><tr><th>Item</th><th>Casos</th><th>% do grupo</th></tr></thead><tbody>{items.map((x,i)=><tr key={`${x.label}-${i}`}><td>{x.label}</td><td>{x.total}</td><td>{total?Math.round((x.total/total)*1000)/10:0}%</td></tr>)}</tbody></table></div>:<p>Sem sinal agregado disponível.</p>}</div>}

export default function ProductionReceptionCausesAudit(){
  const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;(async()=>{try{const token=localStorage.getItem(TOKEN_KEY);if(!token)throw new Error("Sessão administrativa não encontrada.");const next=await apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/whatsapp-reception-causes-v1`,token);if(!cancelled)setData(next);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e));}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true};},[]);
  const pct=(n:number)=>data?.totals.receptionSessions?Math.round((n/data.totals.receptionSessions)*1000)/10:0;
  const priorityDrills=(data?.drilldown||[]).filter(d=>["product_plan_resolution","coverage_resolution","patient_resolution"].includes(d.key));
  return <main className="prod-audit-page"><header className="prod-audit-header"><div><span className="prod-audit-kicker">PRODUÇÃO · SOMENTE LEITURA</span><h1>Causas de encaminhamento à recepção</h1><p>Classificação agregada dos encaminhamentos canônicos. Nenhum dado é alterado.</p></div><button type="button" onClick={()=>window.location.href="/?audit=history-canonical"}>Voltar ao histórico</button></header>{loading&&<section className="prod-audit-card">Classificando encaminhamentos reais…</section>}{error&&<section className="prod-audit-error"><strong>Falha ao carregar.</strong><br/>{error}</section>}{data&&<><section className="prod-audit-grid"><article className="prod-audit-card"><small>Sessões analisadas</small><strong>{data.totals.sessions||0}</strong></article><article className="prod-audit-card"><small>Encaminhadas à recepção</small><strong>{data.totals.receptionSessions||0}</strong></article><article className="prod-audit-card"><small>Confiança alta</small><strong>{data.totals.classifiedHighConfidence||0}</strong></article><article className="prod-audit-card"><small>Confiança média</small><strong>{data.totals.classifiedMediumConfidence||0}</strong></article><article className="prod-audit-card"><small>Baixa / inconclusiva</small><strong>{data.totals.unclassifiedLowConfidence||0}</strong></article></section>{data.calibration&&<section className={data.calibration.ok?"prod-audit-card":"prod-audit-error"}><h2>{data.calibration.ok?"Calibração: OK":"Calibração: DIVERGENTE"}</h2><p>Recepção canônica de referência: <b>{data.calibration.canonicalReceptionSessions}</b> · Sessões classificadas: <b>{data.calibration.classifiedReceptionSessions}</b> · Delta: <b>{data.calibration.delta}</b>.</p><p>{data.calibration.authority}</p></section>}<section className="prod-audit-card"><h2>Distribuição das causas</h2><p>{data.methodology.caution}</p><div className="prod-audit-table-wrap"><table><thead><tr><th>Causa provável</th><th>Total</th><th>Alta confiança</th><th>Média</th><th>Baixa</th><th>% recepção</th></tr></thead><tbody>{data.causes.map(c=><tr key={c.key}><td><b>{c.label}</b><br/><small>{c.total} casos · {pct(c.total)}% da recepção</small></td><td>{c.total}</td><td>{c.high}</td><td>{c.medium}</td><td>{c.low}</td><td>{pct(c.total)}%</td></tr>)}</tbody></table></div></section>{priorityDrills.map(d=><section className="prod-audit-card" key={d.key}><h2>{d.label}</h2><p><b>{d.total} casos</b> · {pct(d.total)}% de todos os encaminhamentos à recepção.</p><MiniList title="Por convênio" items={d.topCoverages} total={d.total}/><MiniList title="Por especialidade" items={d.topSpecialties} total={d.total}/><MiniList title="Subsinal estruturado" items={d.subSignals} total={d.total}/></section>)}<section className="prod-audit-card"><p><b>Fonte:</b> {data.methodology.source}</p><p>{data.methodology.privacy}</p></section></>}</main>;
}
