import { useEffect, useMemo, useState } from "react";
import "./productionCoverageAudit.css";

const API_BASE=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/+$/,"");
const TOKEN_KEY="agendai_admin_token";
const CLIENTE_ID=1;

type Doctor={medicoId:number;nome:string;ativo:boolean;specialties:number;activeTotal:number;inactiveTotal:number;generalActive:number;specificActive:number;distinctInsurers:number;distinctProducts:number;model:string};
type AuditData={generatedAt:string;totals:Record<string,number>;doctors:Doctor[];professionalPriorityFieldCandidates:Array<{table:string;column:string;dataType:string}>;tableCounts:Record<string,number|null>;whatsappHistory:{firstAt:string|null;lastAt:string|null;total:number|null;byMonth:Array<{month:string;total:number}>}};
type AnalysisData={totals:Record<string,number>;priorityFindings:any[];methodology:{warning:string}};
type ExecutivePriority={medicoId:number;medico:string;convenioId:number;convenio:string;status:string;confidence:string;severity:number;specificProducts:number;generalRows:number;peerMedianSpecificProducts:number;reason:string};
type ExecutiveInsurer={convenioId:number;convenio:string;totalScopes:number;criticalGap:number;probableUndercoverage:number;reviewUndercoverage:number;reviewOvercoverage:number;inconclusiveGeneralRule:number;coherentPattern:number;attentionRate:number;score:number};
type ExecutiveData={totals:Record<string,number>;insurers:ExecutiveInsurer[];priorities:ExecutivePriority[];methodology:{interpretation:string;nextValidationLayer:string}};
type HistoryDiscovery={privacy:{note:string};whatsappMessageLogs:{columns:Array<{name:string;dataType:string;nullable:boolean}>;indexes:Array<{name:string;definition:string}>;bounds:{total:number|null;firstAt:string|null;lastAt:string|null};categoricalDistributions:Record<string,Array<{value:string;total:number}>>;jsonTopLevelKeys:Record<string,Array<{key:string;rows:number}>>};relatedTables:Array<{table:string;count:number|null;columns:Array<{name:string;dataType:string}>}>};
type DistItem={value:string;total:number};
type HistoryAnalysis={totals:Record<string,number>;range:{firstSessionAt:string|null;lastSessionAt:string|null};distributions:{stage:DistItem[];intent:DistItem[];reason:DistItem[]};methodology:{privacy:string;warning:string}};
type FunnelRow={outcome:string;sessions:number;withReceptionStage:number;withTechnicalFailure:number;withPendingProductSignal:number;withPatientPreflight:number;withNewConsultationPolicy:number};
type HistoryFunnel={totals:Record<string,number>;funnel:FunnelRow[];methodology:{interpretation:string;caution:string}};

async function apiGet(path:string,token:string){const response=await fetch(`${API_BASE}${path}${path.includes("?")?"&":"?"}t=${Date.now()}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"},cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok||!payload?.ok)throw new Error(payload?.details||payload?.error||`HTTP ${response.status}`);return payload.data;}
function statusLabel(status:string){if(status==="critical_gap")return"CRÍTICO";if(status==="probable_undercoverage")return"PROVÁVEL SUBCOBERTURA";if(status==="review_undercoverage")return"REVISAR COBERTURA";if(status==="review_overcoverage")return"REVISAR EXPANSÃO";if(status==="inconclusive_general_rule")return"INCONCLUSIVO";return"COERENTE";}
function funnelLabel(outcome:string){const labels:Record<string,string>={booking_signal:"Booking confirmado por sinal estruturado",availability_reached_no_booking:"Chegou à disponibilidade, sem booking",doctor_options_no_availability:"Teve opções de médico, sem disponibilidade",eligibility_no_doctor_options:"Chegou à elegibilidade, sem opções de médico",coverage_no_eligibility:"Cobertura resolvida, sem elegibilidade médica",specialty_feegow_no_coverage:"Especialidade Feegow resolvida, sem resolução de cobertura",insurance_specialty_no_resolution:"Convênio + especialidade coletados, sem resolução",booking_intent_incomplete_data:"Intenção de agendar, dados incompletos",outside_booking_or_insufficient_signal:"Fora do fluxo / sinal insuficiente"};return labels[outcome]||outcome;}

export default function ProductionCoverageAudit(){
  const[data,setData]=useState<AuditData|null>(null);const[analysis,setAnalysis]=useState<AnalysisData|null>(null);const[executive,setExecutive]=useState<ExecutiveData|null>(null);const[history,setHistory]=useState<HistoryDiscovery|null>(null);const[historyAnalysis,setHistoryAnalysis]=useState<HistoryAnalysis|null>(null);const[historyFunnel,setHistoryFunnel]=useState<HistoryFunnel|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");
  useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError("");try{const token=localStorage.getItem(TOKEN_KEY);if(!token)throw new Error("Sessão administrativa não encontrada. Entre no painel e abra novamente a auditoria.");const[audit,analysisData,executiveData,historyData,historyAnalysisData,historyFunnelData]=await Promise.all([apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/coverage-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/coverage-analysis-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/coverage-executive-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/whatsapp-history-discovery-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/whatsapp-history-analysis-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/whatsapp-history-funnel-v1`,token)]);if(!cancelled){setData(audit);setAnalysis(analysisData);setExecutive(executiveData);setHistory(historyData);setHistoryAnalysis(historyAnalysisData);setHistoryFunnel(historyFunnelData);}}catch(err){if(!cancelled)setError(err instanceof Error?err.message:String(err));}finally{if(!cancelled)setLoading(false);}}load();return()=>{cancelled=true};},[]);
  const doctors=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return data?.doctors||[];return(data?.doctors||[]).filter(d=>d.nome.toLowerCase().includes(q));},[data,search]);
  return <main className="prod-audit-page">
    <header className="prod-audit-header"><div><span className="prod-audit-kicker">PRODUÇÃO · SOMENTE LEITURA</span><h1>Auditoria de cobertura Angel</h1><p>Nenhum controle desta tela altera aceites, WhatsApp, Feegow ou banco de dados.</p></div><button type="button" onClick={()=>{window.location.href=window.location.pathname;}}>Voltar ao painel</button></header>
    {loading&&<section className="prod-audit-card">Analisando dados reais de produção…</section>}
    {error&&<section className="prod-audit-error"><strong>Falha ao carregar auditoria.</strong><br/>{error}</section>}
    {data&&!loading&&<>
      <section className="prod-audit-grid"><article className="prod-audit-card"><small>Médicos</small><strong>{data.totals.doctors??0}</strong></article><article className="prod-audit-card"><small>Aceites ativos</small><strong>{data.totals.activeAcceptanceRows??0}</strong></article><article className="prod-audit-card"><small>Regras gerais</small><strong>{data.totals.generalAcceptanceRows??0}</strong></article><article className="prod-audit-card"><small>Vínculos específicos</small><strong>{data.totals.specificAcceptanceRows??0}</strong></article><article className="prod-audit-card"><small>Logs WhatsApp persistidos</small><strong>{data.whatsappHistory.total??"—"}</strong></article></section>
      {executive&&<section className="prod-audit-card"><h2>Resumo executivo</h2><p>{executive.methodology.interpretation}</p><div className="prod-audit-counts"><span>Críticos: <b>{executive.totals.criticalGap||0}</b></span><span>Provável subcobertura: <b>{executive.totals.probableUndercoverage||0}</b></span><span>Revisar cobertura: <b>{executive.totals.reviewUndercoverage||0}</b></span><span>Revisar expansão: <b>{executive.totals.reviewOvercoverage||0}</b></span><span>Inconclusivos por regra geral: <b>{executive.totals.inconclusiveGeneralRule||0}</b></span><span>Coerentes: <b>{executive.totals.coherentPattern||0}</b></span></div><h2>Convênios com maior prioridade</h2><div className="prod-audit-table-wrap"><table><thead><tr><th>Convênio</th><th>Escopos</th><th>Críticos</th><th>Provável subcobertura</th><th>Revisar</th><th>% atenção</th></tr></thead><tbody>{executive.insurers.slice(0,25).map(i=><tr key={i.convenioId}><td>{i.convenio}</td><td>{i.totalScopes}</td><td>{i.criticalGap}</td><td>{i.probableUndercoverage}</td><td>{i.reviewUndercoverage}</td><td>{i.attentionRate}%</td></tr>)}</tbody></table></div><h2>Casos prioritários</h2><div className="prod-audit-table-wrap"><table><thead><tr><th>Status</th><th>Médico</th><th>Convênio</th><th>Produtos</th><th>Mediana pares</th><th>Confiança</th><th>Evidência</th></tr></thead><tbody>{executive.priorities.slice(0,100).map((p,i)=><tr key={`${p.medicoId}-${p.convenioId}-${i}`}><td>{statusLabel(p.status)}</td><td>{p.medico}</td><td>{p.convenio}</td><td>{p.specificProducts}</td><td>{Math.round(p.peerMedianSpecificProducts)}</td><td>{p.confidence}</td><td>{p.reason}</td></tr>)}</tbody></table></div><p><b>Próxima validação:</b> {executive.methodology.nextValidationLayer}</p></section>}
      {historyFunnel&&<section className="prod-audit-card"><h2>Funil histórico por ponto mais avançado</h2><p>{historyFunnel.methodology.interpretation}</p><p>{historyFunnel.methodology.caution}</p><div className="prod-audit-counts"><span>Sessões: <b>{historyFunnel.totals.sessions||0}</b></span><span>Bookings por sinal: <b>{historyFunnel.totals.bookingSignalSessions||0}</b></span><span>Elegíveis para análise de perda: <b>{historyFunnel.totals.eligibleForLossAnalysis||0}</b></span><span>Com recepção: <b>{historyFunnel.totals.receptionOverlaySessions||0}</b></span><span>Com falha técnica: <b>{historyFunnel.totals.technicalFailureOverlaySessions||0}</b></span><span>Com produto pendente: <b>{historyFunnel.totals.pendingProductOverlaySessions||0}</b></span></div><div className="prod-audit-table-wrap"><table><thead><tr><th>Ponto mais avançado</th><th>Sessões</th><th>Recepção</th><th>Falha técnica</th><th>Produto pendente</th><th>Preflight paciente</th><th>Política nova consulta</th></tr></thead><tbody>{historyFunnel.funnel.map(r=><tr key={r.outcome}><td>{funnelLabel(r.outcome)}</td><td>{r.sessions}</td><td>{r.withReceptionStage}</td><td>{r.withTechnicalFailure}</td><td>{r.withPendingProductSignal}</td><td>{r.withPatientPreflight}</td><td>{r.withNewConsultationPolicy}</td></tr>)}</tbody></table></div></section>}
      {historyAnalysis&&<section className="prod-audit-card"><h2>Reconstrução histórica por sessão</h2><p>{historyAnalysis.methodology.warning}</p><div className="prod-audit-counts"><span>Sessões identificadas: <b>{historyAnalysis.totals.sessions??0}</b></span><span>Com intenção de agendar: <b>{historyAnalysis.totals.bookingIntentSessions??0}</b></span><span>Com sinal de booking: <b>{historyAnalysis.totals.bookingSignalSessions??0}</b></span><span>Intenção sem sinal de booking: <b>{historyAnalysis.totals.bookingIntentWithoutBookingSignal??0}</b></span><span>Chegaram a estágio de recepção: <b>{historyAnalysis.totals.receptionStageSessions??0}</b></span><span>Sessões com falha técnica: <b>{historyAnalysis.totals.failedSessions??0}</b></span><span>Com convênio coletado: <b>{historyAnalysis.totals.sessionsWithConvenio??0}</b></span><span>Com especialidade coletada: <b>{historyAnalysis.totals.sessionsWithSpecialty??0}</b></span><span>Com resolução de cobertura: <b>{historyAnalysis.totals.sessionsWithCoverageResolution??0}</b></span><span>Com elegibilidade médica: <b>{historyAnalysis.totals.sessionsWithDoctorEligibility??0}</b></span><span>Produto pendente: <b>{historyAnalysis.totals.sessionsWithPendingProduct??0}</b></span><span>Opções de médico: <b>{historyAnalysis.totals.sessionsWithDoctorOptions??0}</b></span><span>Disponibilidade médica: <b>{historyAnalysis.totals.sessionsWithDoctorAvailability??0}</b></span><span>Taxa aparente de booking: <b>{historyAnalysis.totals.apparentBookingRatePct??0}%</b></span></div><h2>Stages mais frequentes</h2><div className="prod-audit-counts">{historyAnalysis.distributions.stage.slice(0,30).map(i=><span key={`stage-${i.value}`}><code>{i.value}</code>: <b>{i.total}</b></span>)}</div><h2>Intents mais frequentes</h2><div className="prod-audit-counts">{historyAnalysis.distributions.intent.slice(0,30).map(i=><span key={`intent-${i.value}`}><code>{i.value}</code>: <b>{i.total}</b></span>)}</div><h2>Reasons estruturados</h2><div className="prod-audit-counts">{historyAnalysis.distributions.reason.slice(0,40).map(i=><span key={`reason-${i.value}`}><code>{i.value}</code>: <b>{i.total}</b></span>)}</div></section>}
      {history&&<section className="prod-audit-card"><h2>Diagnóstico histórico do WhatsApp</h2><p>{history.privacy.note}</p><div className="prod-audit-counts"><span>Linhas: <b>{history.whatsappMessageLogs.bounds.total??"—"}</b></span><span>Colunas: <b>{history.whatsappMessageLogs.columns.length}</b></span><span>Índices: <b>{history.whatsappMessageLogs.indexes.length}</b></span><span>Tabelas relacionadas: <b>{history.relatedTables.length}</b></span></div><h2>Campos disponíveis em whatsapp_message_logs</h2><div className="prod-audit-counts">{history.whatsappMessageLogs.columns.map(c=><span key={c.name}><code>{c.name}</code> · {c.dataType}</span>)}</div>{Object.entries(history.whatsappMessageLogs.categoricalDistributions).map(([col,items])=><div key={col}><h2>Distribuição: {col}</h2><div className="prod-audit-counts">{items.map(item=><span key={`${col}-${item.value}`}><code>{item.value}</code>: <b>{item.total}</b></span>)}</div></div>)}{Object.entries(history.whatsappMessageLogs.jsonTopLevelKeys).map(([col,items])=><div key={col}><h2>Chaves JSON: {col}</h2><div className="prod-audit-counts">{items.slice(0,40).map(item=><span key={`${col}-${item.key}`}><code>{item.key}</code>: <b>{item.rows}</b></span>)}</div></div>)}<h2>Tabelas relacionadas encontradas</h2><div className="prod-audit-table-wrap"><table><thead><tr><th>Tabela</th><th>Linhas</th><th>Campos relevantes</th></tr></thead><tbody>{history.relatedTables.map(t=><tr key={t.table}><td><code>{t.table}</code></td><td>{t.count??"—"}</td><td>{t.columns.map(c=>c.name).slice(0,18).join(", ")}</td></tr>)}</tbody></table></div></section>}
      {analysis&&<section className="prod-audit-card"><h2>Camada estatística</h2><p>{analysis.methodology.warning}</p></section>}
      <section className="prod-audit-card"><h2>Histórico disponível</h2><p>Primeiro log: {data.whatsappHistory.firstAt?new Date(data.whatsappHistory.firstAt).toLocaleString("pt-BR"):"não identificado"}</p><p>Último log: {data.whatsappHistory.lastAt?new Date(data.whatsappHistory.lastAt).toLocaleString("pt-BR"):"não identificado"}</p><div className="prod-audit-months">{data.whatsappHistory.byMonth.map(item=><span key={item.month}>{item.month}: <b>{item.total}</b></span>)}</div></section>
      <section className="prod-audit-card"><div className="prod-audit-title-row"><div><h2>Distribuição real por profissional</h2><p>Regra geral = aceite sem produto específico. Específico = aceite ligado a produto/plano/rede.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar médico"/></div><div className="prod-audit-table-wrap"><table><thead><tr><th>Médico</th><th>Esp.</th><th>Ativos</th><th>Inativos</th><th>Gerais</th><th>Específicos</th><th>Convênios</th><th>Produtos</th><th>Modelo</th></tr></thead><tbody>{doctors.map(d=><tr key={d.medicoId}><td>{d.nome}</td><td>{d.specialties}</td><td>{d.activeTotal}</td><td>{d.inactiveTotal}</td><td>{d.generalActive}</td><td>{d.specificActive}</td><td>{d.distinctInsurers}</td><td>{d.distinctProducts}</td><td>{d.model}</td></tr>)}</tbody></table></div></section>
      <section className="prod-audit-card"><h2>Campos candidatos a prioridade / sócio / agregado</h2>{data.professionalPriorityFieldCandidates.length===0?<p>Nenhum campo candidato foi encontrado nas tabelas pesquisadas.</p>:<ul>{data.professionalPriorityFieldCandidates.map(field=><li key={`${field.table}.${field.column}`}><code>{field.table}.{field.column}</code> · {field.dataType}</li>)}</ul>}</section>
      <section className="prod-audit-card"><h2>Contagem das tabelas críticas</h2><div className="prod-audit-counts">{Object.entries(data.tableCounts).map(([name,total])=><span key={name}><code>{name}</code>: <b>{total??"não disponível"}</b></span>)}</div></section>
    </>}
  </main>;
}
