import { useEffect, useMemo, useState } from "react";
import "./productionCoverageAudit.css";

const API_BASE=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/+$/,"");
const TOKEN_KEY="agendai_admin_token";
const CLIENTE_ID=1;

type Doctor={medicoId:number;nome:string;ativo:boolean;specialties:number;activeTotal:number;inactiveTotal:number;generalActive:number;specificActive:number;distinctInsurers:number;distinctProducts:number;model:string};
type AuditData={generatedAt:string;totals:Record<string,number>;doctors:Doctor[];professionalPriorityFieldCandidates:Array<{table:string;column:string;dataType:string}>;tableCounts:Record<string,number|null>;whatsappHistory:{firstAt:string|null;lastAt:string|null;total:number|null;byMonth:Array<{month:string;total:number}>}};
type Finding={medicoId:number;medico:string;convenioId:number;convenio:string;generalRows:number;specificProducts:number;peerMedianSpecificProducts:number;classification:string;confidence:string;severity:number;reason:string};
type AnalysisData={totals:Record<string,number>;priorityFindings:Finding[];methodology:{warning:string}};
type ExecutivePriority={medicoId:number;medico:string;convenioId:number;convenio:string;status:string;confidence:string;severity:number;specificProducts:number;generalRows:number;peerMedianSpecificProducts:number;reason:string};
type ExecutiveInsurer={convenioId:number;convenio:string;totalScopes:number;criticalGap:number;probableUndercoverage:number;reviewUndercoverage:number;reviewOvercoverage:number;inconclusiveGeneralRule:number;coherentPattern:number;attentionRate:number;score:number};
type ExecutiveData={totals:Record<string,number>;insurers:ExecutiveInsurer[];priorities:ExecutivePriority[];methodology:{interpretation:string;nextValidationLayer:string}};

async function apiGet(path:string,token:string){const response=await fetch(`${API_BASE}${path}${path.includes("?")?"&":"?"}t=${Date.now()}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"},cache:"no-store"});const payload=await response.json().catch(()=>null);if(!response.ok||!payload?.ok)throw new Error(payload?.details||payload?.error||`HTTP ${response.status}`);return payload.data;}

function statusLabel(status:string){if(status==="critical_gap")return"CRÍTICO";if(status==="probable_undercoverage")return"PROVÁVEL SUBCOBERTURA";if(status==="review_undercoverage")return"REVISAR COBERTURA";if(status==="review_overcoverage")return"REVISAR EXPANSÃO";if(status==="inconclusive_general_rule")return"INCONCLUSIVO";return"COERENTE";}

export default function ProductionCoverageAudit(){
  const[data,setData]=useState<AuditData|null>(null);const[analysis,setAnalysis]=useState<AnalysisData|null>(null);const[executive,setExecutive]=useState<ExecutiveData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");
  useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError("");try{const token=localStorage.getItem(TOKEN_KEY);if(!token)throw new Error("Sessão administrativa não encontrada. Entre no painel e abra novamente a auditoria.");const[audit,analysisData,executiveData]=await Promise.all([apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/coverage-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/coverage-analysis-v1`,token),apiGet(`/api/admin/clientes/${CLIENTE_ID}/prod-audit/coverage-executive-v1`,token)]);if(!cancelled){setData(audit);setAnalysis(analysisData);setExecutive(executiveData);}}catch(err){if(!cancelled)setError(err instanceof Error?err.message:String(err));}finally{if(!cancelled)setLoading(false);}}load();return()=>{cancelled=true};},[]);
  const doctors=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return data?.doctors||[];return(data?.doctors||[]).filter(d=>d.nome.toLowerCase().includes(q));},[data,search]);
  return <main className="prod-audit-page">
    <header className="prod-audit-header"><div><span className="prod-audit-kicker">PRODUÇÃO · SOMENTE LEITURA</span><h1>Auditoria de cobertura Angel</h1><p>Nenhum controle desta tela altera aceites, WhatsApp, Feegow ou banco de dados.</p></div><button type="button" onClick={()=>{window.location.href=window.location.pathname;}}>Voltar ao painel</button></header>
    {loading&&<section className="prod-audit-card">Analisando dados reais de produção…</section>}
    {error&&<section className="prod-audit-error"><strong>Falha ao carregar auditoria.</strong><br/>{error}</section>}
    {data&&!loading&&<>
      <section className="prod-audit-grid"><article className="prod-audit-card"><small>Médicos</small><strong>{data.totals.doctors??0}</strong></article><article className="prod-audit-card"><small>Aceites ativos</small><strong>{data.totals.activeAcceptanceRows??0}</strong></article><article className="prod-audit-card"><small>Regras gerais</small><strong>{data.totals.generalAcceptanceRows??0}</strong></article><article className="prod-audit-card"><small>Vínculos específicos</small><strong>{data.totals.specificAcceptanceRows??0}</strong></article><article className="prod-audit-card"><small>Logs WhatsApp persistidos</small><strong>{data.whatsappHistory.total??"—"}</strong></article></section>
      {executive&&<section className="prod-audit-card"><h2>Resumo executivo</h2><p>{executive.methodology.interpretation}</p><div className="prod-audit-counts"><span>Críticos: <b>{executive.totals.criticalGap||0}</b></span><span>Provável subcobertura: <b>{executive.totals.probableUndercoverage||0}</b></span><span>Revisar cobertura: <b>{executive.totals.reviewUndercoverage||0}</b></span><span>Revisar expansão: <b>{executive.totals.reviewOvercoverage||0}</b></span><span>Inconclusivos por regra geral: <b>{executive.totals.inconclusiveGeneralRule||0}</b></span><span>Coerentes: <b>{executive.totals.coherentPattern||0}</b></span></div><h2>Convênios com maior prioridade</h2><div className="prod-audit-table-wrap"><table><thead><tr><th>Convênio</th><th>Escopos</th><th>Críticos</th><th>Provável subcobertura</th><th>Revisar</th><th>% atenção</th></tr></thead><tbody>{executive.insurers.slice(0,25).map(i=><tr key={i.convenioId}><td>{i.convenio}</td><td>{i.totalScopes}</td><td>{i.criticalGap}</td><td>{i.probableUndercoverage}</td><td>{i.reviewUndercoverage}</td><td>{i.attentionRate}%</td></tr>)}</tbody></table></div><h2>Casos prioritários</h2><div className="prod-audit-table-wrap"><table><thead><tr><th>Status</th><th>Médico</th><th>Convênio</th><th>Produtos</th><th>Mediana pares</th><th>Confiança</th><th>Evidência</th></tr></thead><tbody>{executive.priorities.slice(0,100).map((p,i)=><tr key={`${p.medicoId}-${p.convenioId}-${i}`}><td>{statusLabel(p.status)}</td><td>{p.medico}</td><td>{p.convenio}</td><td>{p.specificProducts}</td><td>{Math.round(p.peerMedianSpecificProducts)}</td><td>{p.confidence}</td><td>{p.reason}</td></tr>)}</tbody></table></div><p><b>Próxima validação:</b> {executive.methodology.nextValidationLayer}</p></section>}
      {analysis&&<section className="prod-audit-card"><h2>Camada estatística</h2><p>{analysis.methodology.warning}</p></section>}
      <section className="prod-audit-card"><h2>Histórico disponível</h2><p>Primeiro log: {data.whatsappHistory.firstAt?new Date(data.whatsappHistory.firstAt).toLocaleString("pt-BR"):"não identificado"}</p><p>Último log: {data.whatsappHistory.lastAt?new Date(data.whatsappHistory.lastAt).toLocaleString("pt-BR"):"não identificado"}</p><div className="prod-audit-months">{data.whatsappHistory.byMonth.map(item=><span key={item.month}>{item.month}: <b>{item.total}</b></span>)}</div></section>
      <section className="prod-audit-card"><div className="prod-audit-title-row"><div><h2>Distribuição real por profissional</h2><p>Regra geral = aceite sem produto específico. Específico = aceite ligado a produto/plano/rede.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar médico"/></div><div className="prod-audit-table-wrap"><table><thead><tr><th>Médico</th><th>Esp.</th><th>Ativos</th><th>Inativos</th><th>Gerais</th><th>Específicos</th><th>Convênios</th><th>Produtos</th><th>Modelo</th></tr></thead><tbody>{doctors.map(d=><tr key={d.medicoId}><td>{d.nome}</td><td>{d.specialties}</td><td>{d.activeTotal}</td><td>{d.inactiveTotal}</td><td>{d.generalActive}</td><td>{d.specificActive}</td><td>{d.distinctInsurers}</td><td>{d.distinctProducts}</td><td>{d.model}</td></tr>)}</tbody></table></div></section>
      <section className="prod-audit-card"><h2>Campos candidatos a prioridade / sócio / agregado</h2>{data.professionalPriorityFieldCandidates.length===0?<p>Nenhum campo candidato foi encontrado nas tabelas pesquisadas.</p>:<ul>{data.professionalPriorityFieldCandidates.map(field=><li key={`${field.table}.${field.column}`}><code>{field.table}.{field.column}</code> · {field.dataType}</li>)}</ul>}</section>
      <section className="prod-audit-card"><h2>Contagem das tabelas críticas</h2><div className="prod-audit-counts">{Object.entries(data.tableCounts).map(([name,total])=><span key={name}><code>{name}</code>: <b>{total??"não disponível"}</b></span>)}</div></section>
    </>}
  </main>;
}
